a=5
a
a=5
a
class(a)
a=5
a
class(a)
b="c"
b
class(b)
a=5
a
class(a)
b="c"
b
class(b)
b="5"
b
class(b)
a=5
a
class(a)
b='c'
b
class(b)
b="5"
b
class(b)
a=c(2,3,4,5)
a
b=c("2","3")
b
b=c("2","3")
b
a=c(2,3,4,5)
a
b=c(2,"3")
b
a=c(2,3,4,5)
a
b=c(2,"3")
b
class(b)
a=c(2,3,4,5)
a
b=c(2,"3")
b
class(b)
class(a)
a=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE)
a
b=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=FALSE)
b
c=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3)
c
a=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE)
a
b=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=FALSE)
b
c=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3)
c
a[1,]
a[,1]
a=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE)
a
b=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=FALSE)
b
c=matrix(c(1,2,3,4,5,6),nrow=2,ncol=3)
c
a[1,]
a[,1]
class(a)
a=read.csv("dataset1.csv")
a
setwd("C:\Users\Admin\Desktop\Dataset")
p=read.csv("dataset1.csv")
setwd("C:/Users/Admin/Desktop/Dataset")
p=read.csv("dataset1.csv")
setwd("C:/Users/Admin/Desktop/Dataset")
p=read.csv("dataset1.csv")
p
setwd("C:/Users/Admin/Desktop/Dataset")
p=read.csv("dataset1.csv")
p
class(p)
setwd("C:/Users/Admin/Desktop/Dataset")
p=read.csv("dataset1.csv")
p
p$Height
setwd("C:/Users/Admin/Desktop/Dataset")
p=read.csv("dataset1.csv")
p
p$Height
p$Girth
Name=c("a","b","c")
English=c(1,2,3)
Maths=c(1,2,3)
Science=c(1,2,3)
c=data.frame(Name,English,Maths,Science)
Name=c("a","b","c")
English=c(1,2,3)
Maths=c(1,2,3)
Science=c(1,2,3)
c=data.frame(Name,English,Maths,Science)
c
Name=c("a","b","c")
English=c(1,2,3)
Maths=c(1,2,3)
Science=c(1,2,3)
c=data.frame(Name,English,Maths,Science)
c